name: Run Python 2
env: 
  USER: ${{ secrets.USER }}
  PASS: ${{ secrets.PASS }}
  URL: ${{ secrets.URL2 }}
  API_KEY: ${{ secrets.API_KEY }}

on:
  schedule: 
    - cron: '0/10 6-20 8-10 12 *'
    - cron: '0/20 21-23,0-5 8-10 12 *'
#    - cron: '0/20 0 11 12 *'
  workflow_dispatch:


jobs:

  update:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt
    - run: python script2.py
